version: '3'

volumes:
    anne-db-data:

services:
    database:
        image: 'postgres'
        container_name: 'anne-postgres-container'
        env_file:
            - ./env/anne-postgres.env
        volumes:
            - anne-db-data:/var/lib/postgres/data/
        ports:
            - 5434:5432
